POST http://localhost:8080/missions/add
Content-Type: application/json

{
  "point": 5000,
  "standardAmount": 15000,
  "endDate": "2025-12-20T14:30:00",
  "managerId": 1,
  "storeId": 2
}
###
GET http://localhost:8080/missions/2